### PR TITLE
Fix bug #44

### LINKED ISSUE #44: [Cooperations] A user can update both price and status at the same time
**Description:** A user can update both price and status of cooperation at the same time

**Reproducible:** always.

**Preconditions:**
The user is logged in.

**Steps to reproduce:**
1. Set price and status in body, then update a cooperation

**Actual result:**
A coopration updated

**Expected result:**
A forbidden error must appear

### PR DESCRIPTION
**Pull request by iva-stasia**
Fix bug #44: A user can update both cooperation price and status at the same time.

Fixed by adding a new check if the price and status are passed at the same time. If so, a forbidden error is thrown.

Screenshot 2024-02-09 at 12 10 49

### CODE REVIEW

**Review by Wiret02 — APPROVED** [review]

**Review by StasRusnak1 — APPROVED** [review]

**Review by holus-bolus — APPROVED** [review]

**Review by iaremchuk — APPROVED** [review]

File: services/cooperation.js [hunk 1]
```diff
@@ -32,6 +32,8 @@ const cooperationService = {
     const { role: currentUserRole } = currentUser
     const { price, status } = updateData
 
+    if (price && status) throw createForbiddenError()
```
Comment (vlad-khrychov) [inline services/cooperation.js]: According to the model price has `Number` type. So, if we obtain new status and new price with 0 value `price && status` will be `false`. That's right? Therefore, this error will not be generated for this case. I see, that `updateCooperation` does not check case when `price===0`.

**Review by vlad-khrychov — APPROVED** [review]
You can create new bug if it is relevant  for zero cost cooperation.

File: services/cooperation.js (hunk 1 above)
Comment (iva-stasia) [reply services/cooperation.js]: Indeed, I missed it. Changed the condition ✅
